services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5196:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=Nexora;Username=Nexora;Password=${POSTGRES_PASSWORD};GSS Encryption Mode=Disable"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: Nexora
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: Nexora
    ports:
      - "5434:5432"
    volumes:
      - pg_nexora_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Nexora -d Nexora"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pg_nexora_data:
